### ISSUE TITLE
SVG on error pages not rendering on Safari

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#63]
- Seems that "error" SVG fails to render on Safari. When I view the error pages, I see a blank page. So, most likely this is an Apple "bug."

- iPhone:
![IMG_9299](https://user-images.githubusercontent.com/1673222/121806110-88a48000-cc89-11eb-976f-7d4114344df2.jpeg)

- PC::Safari 14.1
![Screen Shot 2021-06-13 at 23 06 30](https://user-images.githubusercontent.com/1673222/121810505-20ab6500-cc9c-11eb-8476-189fd361cecc.png)

* I've done some minor research and found a few articles that may help:
- https://css-tricks.com/heres-how-i-solved-a-weird-bug-using-tried-and-true-debugging-strategies/
- https://developer.apple.com/forums/thread/673678
- https://stackoverflow.com/questions/4504942/mobile-safari-svg-problem
- https://forum.webflow.com/t/svgs-not-showing-on-apple-mobile-devices/3983
- https://youtu.be/ZJSCl6XEdP8

**Comment by lorezyra** [comment]
You may find this interesting : http://svg-wow.org/
After I viewed this site on my iPhone, I can see that most SVG works, but there are some issues. Let's try to keep the SVG as it's the best for scaling between tiny and huge screen sizes.

**Comment by lorezyra** [comment]
![Screen Shot 2021-06-28 at 12 12 37](https://user-images.githubusercontent.com/1673222/123574330-979f3c80-d80a-11eb-8c44-659ff2a45e25.png)

For the LOGO svg, once you changed the `display` to `flex`, it stops working in Safari. I can see it in Chrome, but not on my iPhone and not on my MacBook/iPad.

**Comment by lorezyra** [comment]
By playing with the CSS, I can get it to display. But the footer doesn't properly push down from the error container.
```css

/* Error Pages start */
.container .error {
  height: clamp(30vh, 60vh, 80vh);
  width: clamp(25vw, 60vw, 90vw);
  top: 50px;
  position: relative;
  display: block;
  justify-content: center;
  z-index: 2;
}
```

From this CSS, the mobile view looks okay & the PC view is horrible. Probably need to adjust the footer to respond better.

![image](https://user-images.githubusercontent.com/1673222/123578151-2793b500-d810-11eb-85ad-e56874debf43.png)
