### ISSUE TITLE
Extend BlockQuote tag styling

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#92]
From: https://github.com/lorezyra/Richie2.com/issues/7#issuecomment-887519434

- [x] Let's add the full support of tags associated with `<blockquote>`:

(EXAMPLE:)
```html
<div>
    <blockquote>
    <header>
        <cite>
            (URL reference)
        </cite>
    </header>
        It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who strives valiantly; who errs, who comes short again and again, because there is no effort without error and shortcoming; but who does actually strive to do the deeds; who knows great enthusiasms, the great devotions; who spends himself in a worthy cause; who at the best knows in the end the triumph of high achievement, and who at the worst, if he fails, at least fails while daring greatly, so that his place shall never be with those cold and timid souls who neither know victory nor defeat.
    <footer>
        <cite>
            Teddy Roosevelt
        </cite>
    </footer>
    </blockquote>
</div>
```

```css
blockquote {
    font-family: Georgia, serif;
    position: relative;
    margin: 0.5em;
    padding: 0.5em 2em 0.5em 3em;
}
/* Thanks: http://callmenick.com/post/styling-blockquotes-with-css-pseudo-classes */
blockquote:before {
    font-family: Georgia, serif;
    position: absolute;
    font-size: 6em;
    line-height: 1;
    top: 0;
    left: 0;
    content: "\201C";
}
blockquote:after {
    font-family: Georgia, serif;
    position: absolute;
   /* display: block; don't use this, it raised the quote too high from the bottom - defeated line-height? */
    float:right;
    font-size:6em;
    line-height: 1;
    right:0;
    bottom:-0.5em;
    content: "\201D";
}
blockquote footer {
    padding: 0 2em 0 0;
    text-align:right;
}
blockquote cite:before {
    content: "\2013";
}
```

![image](https://user-images.githubusercontent.com/1673222/127238984-5e6e8f89-16c6-48ea-b90b-a0c992c9475a.png)

Source: https://stackoverflow.com/questions/16325687/make-big-quotes-with-blockquote

---

- [x] Move this CSS out of `project.SCSS` and into a "universal" SCSS that is available for all pages.
- [x] Same for the link styling used on play.html and legal pages. (move to a "universal" SCSS.)
